### ISSUE TITLE
Version 0.3.13 doesn't work properly

### ISSUE THREAD

**Issue by artik** [dubocr/homebridge-tahoma#133]
After the 0.3.12 update, the plugin doesn't work properly. All blinds keep loading to display the status (open or close), the first click on the icon doesn't open it or close blinds even if the log says:

```
[12/2/2019, 9:22:09 PM] [My TaHoma Box] [Salon frigo] setClosure[100]
[12/2/2019, 9:22:11 PM] [My TaHoma Box] [Salon frigo] setClosure COMPLETED
```

This message is display 2 secondes after the command, but no answer from the blind. I have to click again to see a blind movment, and it stays "Updating", "closing" or "Opening". It seems the blinds are not communicating properly with homebridge to give a proper status.

https://i.imgur.com/Qyz52aH.png

I reverted to 0.3.12, even if 2 blinds are inverted, communication between them and homebridge is perfectly done. Working logs from 0.3.12:

```
[12/2/2019, 9:19:38 PM] [My TaHoma Box] [Salon big left] setDeployment[100]
[12/2/2019, 9:19:40 PM] [My TaHoma Box] [Salon big right] setDeployment[100]
[12/2/2019, 9:19:46 PM] [My TaHoma Box] [Salon entrée] setClosure[100]
[12/2/2019, 9:19:50 PM] [My TaHoma Box] [Salon focale] setClosure[100]
[12/2/2019, 9:19:57 PM] [My TaHoma Box] [Salon terrasse] setClosure COMPLETED
[12/2/2019, 9:19:59 PM] [My TaHoma Box] [Salon entrée] setClosure COMPLETED
[12/2/2019, 9:20:03 PM] [My TaHoma Box] [Salon big right] setDeployment COMPLETED
[12/2/2019, 9:20:13 PM] [My TaHoma Box] [Salon focale] setClosure COMPLETED
[12/2/2019, 9:20:19 PM] [My TaHoma Box] [Salon big left] setDeployment COMPLETED
```

 @dubocr if you need more logs / tests, let me know.

**Comment by artik** [comment]
Strange behavior also:

```
[12/2/2019, 11:39:16 PM] [My TaHoma Box] [Bureau centre middle] type: ExteriorScreen > PositionableScreen, protocol: io
[12/2/2019, 11:39:16 PM] [My TaHoma Box] Instanciate Bureau centre middle as WindowCovering
[12/2/2019, 11:39:28 PM] [My TaHoma Box] [Bureau centre middle] setClosure[0]
[12/2/2019, 11:39:28 PM] [My TaHoma Box] [Bureau centre middle] setClosure[0]
[12/2/2019, 11:39:29 PM] [My TaHoma Box] Listener registered c8c4c563-d9b6-8679-1304-85900722309d
[12/2/2019, 11:39:29 PM] [My TaHoma Box] Listener registered c8c4c563-d9b6-8679-1304-85900722309d
[12/2/2019, 11:39:33 PM] [My TaHoma Box] [Bureau centre middle] setClosure ACTUATORNOANSWER
[12/2/2019, 11:39:33 PM] [My TaHoma Box] [Bureau centre middle] setClosure ACTUATORNOANSWER
```

**Comment by URBANsUNITED** [comment]
Yeah!
Since the last update my blinds operate alone. I have different profiles in combination with sun sensor. And these scenes start working even they are deactivated!
Will revert back to the earlier version.

**Comment by artik** [comment]
I noticed that % are inverted too. If I set open at 20%, it closes my blinds at 20%

**Comment by dubocr** [comment]
Must be fixed in 0.3.14

**Comment by artik** [comment]
Thanks @dubocr , but the bug still occurs in 0.3.14 and 0.3.15.

Here is a video : https://www.youtube.com/watch?v=-N-hemCIMKc&feature=youtu.be

And the logs:

```
[12/3/2019, 7:43:41 PM] [My TaHoma Box] [Salon frigo] setClosure[83]
[12/3/2019, 7:43:46 PM] [My TaHoma Box] [Salon frigo] setClosure COMPLETED
```
