### ISSUE TITLE
Error 429 Server Busy

### ISSUE THREAD

**Issue by Jer3m** [dubocr/homebridge-tahoma#208]
Bonjour,

J'ai réactivé l'automatisation, pour la mise en route des chauffages, à une heure précise mais j'ai remarqué qu'ils ne s'allumaient pas malgré la programmation.
À chaque déclenchement de l'automatisation pour le chauffage j'ai le Log suivant:

_14/10/2020 à 07:59:59 [Tahoma] [Chauffage de R.] setHeatingLevel["eco"]
14/10/2020 à 07:59:59 [Tahoma] Error 429 Server busy, please try again later. (Too many executions) (TOO_MANY_OPERATIONS_IN_PROGRESS)
14/10/2020 à 07:59:59 [Tahoma] [Chauffage de R.] setHeatingLevel FAILED_

Mes volets sont aussi automatisés, à une heure précise, mais je ne rencontre pas ce problème, ils se ferment bien comme prévu, à l'heure prévue.

Tous mes appareils sont à jour, j'ai effacé puis refait l'automatisation mais rien n'y fait.
Une idée?

EDIT:
J'ai eu ce Log à 17h30 (je n'ai pas d'automation à cette heure-ci)

_14/10/2020 à 17:31:02 [Tahoma] Error 502
14/10/2020 à 17:31:02 [Tahoma] [EXECPOLLING] Error with listener 11192f96-ac10-3401-2d04-1db385e545f0 => Error 502
14/10/2020 à 17:31:02 [Tahoma] 
14/10/2020 à 17:31:02 [Tahoma] Listener registered 27bc72a5-ac10-3401-2d04-1db32aa599a3
14/10/2020 à 17:31:03 [Tahoma] Error 400 Invalid event listener id : 11192f96-ac10-3401-2d04-1db385e545f0 (UNSPECIFIED_ERROR)
14/10/2020 à 17:31:03 [Tahoma] [EXECPOLLING] Error with listener 27bc72a5-ac10-3401-2d04-1db32aa599a3 => Error 400 Invalid event listener id : 11192f96-ac10-3401-2d04-1db385e545f0 (UNSPECIFIED_ERROR)
14/10/2020 à 17:31:03 [Tahoma] 
14/10/2020 à 17:31:03 [Tahoma] Listener registered 27bc7349-ac10-3401-2d04-1db30f20e5e9_

Cordialement

**Comment by MirkoKas** [comment]
I‘m not speaking French so I translated your message. 
I‘m also running into this issue now and then. As far as I know it’s because Somfy‘s servers are really busy. For me it‘s happening when automations run at very typical hours, like 7:30 or something in the morning and I‘m running only blinds from Somfy by the way. 
What I found is a good workaround, is to run those automations on less typical times like 7:33 or so. But still every now and then the automations still fail - but it’s way, way less often.
Maybe @dubocr could build something into this plugin to catch the error and retry the automation a couple of seconds or so later? This would fix it for sure.

**Comment by iMicknl** [comment]
> As far as I know it’s because Somfy‘s servers are really busy.

The issue is because you are hitting the maximum amount of 10 executions at the same time. We encounter the issue as well in the Home Assistant integration; https://github.com/iMicknl/ha-tahoma/issues/261. 

How many devices do you have and how many actions do you execute at the same time? 

```
Server busy, please try again later. (Too many executions)
Execution queue is full on gateway: #xxxx-xxxx-xxxx (soft limit: 10)
```

**Comment by Jer3m** [comment]
I had a similar problem that has since been solved, which stated "too many request".
I don't know if it's a scheduling problem here or too many requests being sent from my account but for "error 429" I have "too many executions" which reminds me of the old "too many request" problem.
On the other hand, error 502 and error 400 seem really different, but less "serious" because they are not related to an automation.
I will try to change the schedule by a few minutes if it seems to solve the problem sometimes.

Translated with www.DeepL.com/Translator (free version)

**Comment by Jer3m** [comment]
Hello @iMicknl
> How many devices do you have and how many actions do you execute at the same time?
I have 3 devices for this automation

**Comment by MirkoKas** [comment]
Yeah, I used to have several automations a couple of months back, because 19 blinds could not be handled in one automation. But this got fixed in this plugin several month ago and @dubocr found a solution to queue those request to Somfy, when I remember correctly. 
The new HomeKit automation I have, runs very good normally. All blinds open and close how they should. But only from time to time the Somfy server is busy. So, I don't think it's the same issue we had before with HomeKit triggering to many commands, but it's an overflow on Somfy server. As I stated you can play around and execute the same automations a couple of minutes later then typical times and it will help. But with people triggering automations with sunrise or sunset it can get busy one day. So, this problem seems to be something different - and it seems to me that it's on Somfy's side because there are too many request from different customers coming in at the very same time on their server.
Maybe @dubocr could queue those commands in these situations as well and handle them a couple of seconds later!?

**Comment by mhalttu** [comment]
This is still happening, and it is not caused by _your devices_ making too many requests at the same time. As @MirkoKas said, it happens because Somfy's servers are flooded by too many concurrent requests _by everybody_. 

The solution is to not give up on first failure, but to retry with an exponential backoff.
