### ISSUE TITLE
Bad credentials while using cozytouch

### ISSUE THREAD

**Issue by B2nn** [dubocr/homebridge-tahoma#433]
Hello,

First of all, thank you for this useful tool. I currently have two bride: one Tahoma and one CozyTouch.
The Tahoma is working fine. However, the CozyTouch is unable to log in and I still get this error message.
I have seen in the past that API changed and an update for was needed for that (https://github.com/dubocr/overkiz-client/pull/3/commits/3dd8e9c2faa380c310fb0efdc2c85e10299696bc#top)

Here are the logs from the terminal:
[31/10/2022, 21:40:32] [CozyTouch] API client will be locked for 60 seconds because of bad credentials or temporary service outage. You can restart plugin to force login retry (not recommanded except if you think your credentials are wrong).
[31/10/2022, 21:40:32] [CozyTouch] Error 401 Bad credentials (AUTHENTICATION_ERROR)
[31/10/2022, 21:40:32] [CozyTouch] Retry in 60 sec...
[31/10/2022, 21:40:32] [CozyTouch] Fail to load lang file: Error 401 Bad credentials (AUTHENTICATION_ERROR)
[31/10/2022, 21:41:33] [CozyTouch] API client will be locked for 4 minutes because of bad credentials or temporary service outage. You can restart plugin to force login retry (not recommanded except if you think your credentials are wrong).
[31/10/2022, 21:41:33] [CozyTouch] Error 401 Bad credentials (AUTHENTICATION_ERROR)
[31/10/2022, 21:41:33] [CozyTouch] Retry in 120 sec...
[31/10/2022, 21:43:33] [CozyTouch] API client locked. Please check your credentials then restart.
If your credentials are valid, please wait some hours to be unbanned
[31/10/2022, 21:43:33] [CozyTouch] Retry in 240 sec...

Do you think it would be the same issue?

Thank you for your help,
Ben

**Comment by jonasophie** [comment]
Hi same issue for me.
what are you using for "user": e-mail ? pin ? IP ?
Jonas

**Comment by nscheffer** [comment]
Same issue for me with email/password and PIN/Password, didn't try IP

**Comment by B2nn** [comment]
I switched from homebridge to homeassistant and tried their plugin. Same issue is occuring. It seems that Naviclim is the issue as it is not based on overkiz but only on atlantic API. @dubocr , do you confirm?

**Comment by iMicknl** [comment]
@B2nn you probably have a different issue that the others in this thread. What is the error you get using Overkiz in Home Assistant? If you get the message that you don't have supported hardware, it is due to Atlantic not using Overkiz back-end for all their devices.

The Bad Credentials error is due to a change on Atlantics side and this requires code changes in HomeBridge-tahoma (and HA integration as well).

**Comment by dubocr** [comment]
Cozytouch auth endpoint information was updated in release 2.5.52. Should fix this issue.

Thank you @iMicknl and @nscheffer for your help.

**Comment by Ch4rlus** [comment]
Thanks for the update @dubocr. 

I'm not sure if I'm the only one, but I'm still getting issues to connect to Atlantic's Cozycloud : 

When I enter valid credentials, I'm getting a "Error 401 Bad credentials (AUTHENTICATION_ERROR)" error. 
When I enter wrong credentials I'm getting "Error 400 invalid_grant". 

I've double checked the credentials & tested with email + pin code, but none of them seems to work. Also tested on https://dev.duboc.pro/overkiz, doesn't seems to work either. 

I'm running v2.2.52 which should include the newly updated endpoint..

Is there anything I can do to help debug this issue ?
